#include <toltrig/toltrig.hpp>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>
namespace{volatile double sink=0;struct R{const char*n;double l,h;};struct O{std::size_t n=500000;int w=2,t=7;std::string csv="sin-results.csv",cc="record-manually",fl="record-manually";};struct M{double ma=0,mr=0;long double mean=0,rmse=0;std::uint64_t ulp=0;};std::uint64_t bits(double x){std::uint64_t u;std::memcpy(&u,&x,8);constexpr auto s=UINT64_C(1)<<63;return(u&s)?~u:u|s;}std::uint64_t ud(double a,double b){if(a==b)return 0;if(!std::isfinite(a)||!std::isfinite(b))return UINT64_MAX;auto x=bits(a),y=bits(b);return x>y?x-y:y-x;}O parse(int ac,char**av){O o;for(int i=1;i<ac;++i){std::string a=av[i];auto v=[&]{if(++i>=ac)throw std::runtime_error("missing");return std::string(av[i]);};if(a=="--quick"){o.n=20000;o.w=1;o.t=3;}else if(a=="--csv")o.csv=v();else if(a=="--compiler-label")o.cc=v();else if(a=="--flags-label")o.fl=v();else throw std::runtime_error("unknown option");}return o;}std::vector<double> input(R r,std::size_t n,int seed){std::mt19937_64 g(seed);std::uniform_real_distribution<double>d(r.l,r.h);std::vector<double>v(n);for(auto&x:v)x=d(g);return v;}template<class F>double med(const std::vector<double>&v,F f,const O&o){auto run=[&]{double s=0;for(double x:v)s+=f(x);sink=s;};for(int i=0;i<o.w;++i)run();std::vector<double>d;for(int i=0;i<o.t;++i){auto a=std::chrono::steady_clock::now();run();auto b=std::chrono::steady_clock::now();d.push_back(std::chrono::duration<double,std::milli>(b-a).count());}std::sort(d.begin(),d.end());return d[d.size()/2];}template<class F>M err(const std::vector<double>&v,F f){M m;long double ss=0;for(double x:v){double ref=std::sin(x),e=std::fabs(f(x)-ref);m.ma=std::max(m.ma,e);if(ref)m.mr=std::max(m.mr,e/std::fabs(ref));m.ulp=std::max(m.ulp,ud(f(x),ref));m.mean+=e;ss+=e*e;}m.mean/=v.size();m.rmse=std::sqrt(ss/v.size());return m;}const char* platform(){
#if defined(_WIN32)
return"Windows";
#elif defined(__APPLE__)
return"macOS";
#else
return"Linux";
#endif
}void row(std::ofstream&c,const O&o,const char*t,R r,const char*n,double ms,double base,M m={}){c<<platform()<<','<<o.cc<<','<<o.fl<<','<<t<<",\""<<r.n<<"\","<<n<<','<<o.n<<','<<o.w<<','<<o.t<<','<<ms<<','<<ms*1e6/o.n<<','<<base/ms<<','<<m.ma<<','<<m.mean<<','<<m.rmse<<','<<m.mr<<','<<m.ulp<<'\n';}template<class F>void emit(std::ofstream&c,const O&o,const char*t,R r,const char*n,const std::vector<double>&v,double b,F f){row(c,o,t,r,n,med(v,f,o),b,err(v,f));}double rem2(double x){return std::remainder(x,toltrig::two_pi);}double nearpi(double x){return std::nearbyint(x/toltrig::pi);}double nearhalf(double x){return std::nearbyint(x/toltrig::half_pi);}double halfres(double x){double q=std::nearbyint(x/toltrig::half_pi);return x-q*toltrig::half_pi;}double directred(double x){auto r=toltrig::detail::reduce_nearbyint_pi(x);return r.sign*r.value;}double cosshiftred(double x){auto r=toltrig::detail::reduce_nearbyint_pi(toltrig::half_pi-x);return r.sign*r.value;}double remfold(double x){double v=std::remainder(x,toltrig::two_pi);if(v>toltrig::half_pi)v=toltrig::pi-v;else if(v<-toltrig::half_pi)v=-toltrig::pi-v;return v;}}
int main(int ac,char**av){try{O o=parse(ac,av);std::ofstream c(o.csv);c<<"platform,compiler,flags,benchmark_type,range,model,samples,warmup,trials,median_ms,ns_per_sample,speed_ratio_vs_std_sin,max_abs_error,mean_abs_error,rmse,max_relative_error,max_ulp_error\n"<<std::setprecision(17);const R rr[]={{"[-pi/2,pi/2]",-toltrig::half_pi,toltrig::half_pi},{"[-pi,pi]",-toltrig::pi,toltrig::pi},{"[-100,100]",-100,100},{"[-1e6,1e6]",-1e6,1e6}};using namespace toltrig::experimental;auto n7=[](double x){return sin_bounded_n7(x);};auto n8=[](double x){return sin_bounded_n8(x);};auto c7=[](double x){return sin_from_cos_n7(x);};auto c8=[](double x){return sin_from_cos_n8(x);};auto r7=[](double x){return sin_reduced_n7(x);};auto r8=[](double x){return sin_reduced_n8(x);};auto e7=[](double x){return detail::sin_reduced_n7_estrin(x);};auto e8=[](double x){return detail::sin_reduced_n8_estrin(x);};for(int i=0;i<4;++i){auto v=input(rr[i],o.n,20260602+i);double b=med(v,[](double x){return std::sin(x);},o);row(c,o,"full",rr[i],"std_sin",b,b);emit(c,o,"full",rr[i],"sin_from_cos_n7",v,b,c7);emit(c,o,"full",rr[i],"sin_from_cos_n8",v,b,c8);emit(c,o,"full",rr[i],"sin_bounded_n7",v,b,n7);emit(c,o,"full",rr[i],"sin_bounded_n8",v,b,n8);if(i==0){emit(c,o,"polynomial_only",rr[i],"sin_reduced_n7_horner",v,b,r7);emit(c,o,"polynomial_only",rr[i],"sin_reduced_n8_horner",v,b,r8);emit(c,o,"polynomial_only",rr[i],"sin_reduced_n7_estrin",v,b,e7);emit(c,o,"polynomial_only",rr[i],"sin_reduced_n8_estrin",v,b,e8);row(c,o,"call_style",rr[i],"inline_direct",med(v,[](double x){return sin_reduced_n7(x);},o),b,err(v,r7));double(*fp)(double)=sin_reduced_n7;row(c,o,"call_style",rr[i],"function_pointer",med(v,fp,o),b,err(v,fp));}if(i==3){for(auto m:{std::pair<const char*,double(*)(double)>{"std_remainder_two_pi",rem2},{"remainder_sin_fold",remfold},{"nearbyint_div_pi",nearpi},{"nearbyint_div_half_pi",nearhalf},{"nearbyint_half_pi_residual",halfres},{"direct_sin_fold",directred},{"cos_shift_fold",cosshiftred}})row(c,o,"reduction_only",rr[i],m.first,med(v,m.second,o),b);}}std::cout<<"CSV written to "<<o.csv<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
