#include "bench_common.hpp"
#include <iostream>
namespace {
double stdcos(double x){return std::cos(x);} double poly(double x){return toltrig::cos_reduced_n7(x);}
double rem(double x){return std::remainder(x,toltrig::two_pi);} double fmod2(double x){return std::fmod(x,toltrig::two_pi);}
double floorpi(double x){return std::floor(x/toltrig::pi);} double nearpi(double x){return std::nearbyint(x/toltrig::pi);}
double ps(double x){auto r=toltrig::detail::reduce_pi_switch_integer(x);return r.sign*r.value;}
double half(double x){auto r=toltrig::detail::reduce_half_pi_remainder(x);return r.sign*r.value;}
double nearby(double x){auto r=toltrig::detail::reduce_nearbyint_pi(x);return r.sign*r.value;}
struct functor{double operator()(double x)const{return toltrig::cos_reduced_n7(x);}};
}
int main(int argc,char**argv){try{auto o=bench::parse(argc,argv);std::ofstream c(o.csv);bench::header(c);const bench::range rr[]={{"[-pi/2,pi/2]",-toltrig::half_pi,toltrig::half_pi},{"[-pi,pi]",-toltrig::pi,toltrig::pi},{"[-100,100]",-100,100},{"[-1e6,1e6]",-1e6,1e6}};for(int i=0;i<4;++i){auto v=bench::inputs(rr[i],o.samples,o.seed+i);auto base=bench::median_ms(v,stdcos,o);bench::row(c,o,"full",rr[i],"std_cos",base,base);auto emit=[&](const char*t,const char*n,bench::fn f,bool err=false){auto ms=bench::median_ms(v,f,o);bench::row(c,o,t,rr[i],n,ms,base,err?bench::error(v,f):bench::metrics{});};emit("full","bounded_n7",toltrig::cos_bounded_n7,true);emit("full","remainder_n7",toltrig::cos_remainder_n7,true);for(auto m:{std::pair{"std_remainder",rem},{"std_fmod",fmod2},{"floor_div_pi",floorpi},{"nearbyint_div_pi",nearpi},{"pi_switch_integer",ps},{"half_pi_remainder",half},{"nearbyint_pi",nearby}})emit("reduction_only",m.first,m.second);if(i==0){emit("polynomial_only","n7_horner",poly,true);auto direct=bench::median_ms(v,[](double x){return toltrig::cos_reduced_n7(x);},o);bench::row(c,o,"call_style",rr[i],"inline_direct",direct,base,bench::error(v,poly));auto lambda=[](double x){return toltrig::cos_reduced_n7(x);};bench::row(c,o,"call_style",rr[i],"lambda",bench::median_ms(v,lambda,o),base,bench::error(v,lambda));bench::row(c,o,"call_style",rr[i],"template_functor",bench::median_ms(v,functor{},o),base,bench::error(v,functor{}));emit("call_style","function_pointer",poly,true);}}std::cout<<"CSV written to "<<o.csv<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
